RippleCarryAdderD update
microsoft/QuantumLibraries pull request #358
Opened 2020-10-25 12:56 UTC by TviNet

PR for issue #335
Implemented controlled adder blocks following [this paper](https://arxiv.org/abs/1709.06648 ) but use the sum and carry blocks to compute the output carry bit.

2020-10-25 14:27 UTC, msoeken requested changes
Thanks a lot for your pull request @TviNet. It looks already very good. I left some comments.

2020-10-25 14:27 UTC, msoeken commented on Standard/src/Arithmetic/Integer.qs
> +    operation AdderBlockUsingTemporaryLogicalAnd(carryIn: Qubit, summand1: Qubit, summand2: Qubit, carryOut: Qubit)
This operation can be declared `internal` as it is only used for the implementation of `RippleCarryAdderD`.

2020-10-25 14:27 UTC, msoeken commented on Standard/src/Arithmetic/Integer.qs
> +    : Unit is Adj + Ctl {
This operation does not need to be `Ctl`, since it is only called inside a `within` block. Then the controlled blocks can be removed and also the `body (...)` line can be removed, as it will be the only specialisation (the `adjoint` can be generated automatically).

2020-10-25 14:27 UTC, msoeken commented on Standard/src/Arithmetic/Integer.qs
> +                    ApplyAnd (xs![0], ys![0], auxRegister[0]);
It should be possible to merge these nested `within / apply` blocks by moving this `ApplyAnd` operation call before the `for` loop in the nested `within` block.

2020-10-25 14:27 UTC, msoeken commented on Standard/src/Arithmetic/Integer.qs
> +                            (Controlled AdderBlockUsingTemporaryLogicalAnd) (controls, (auxRegister[idx-1], xs![idx], ys![idx], auxRegister[idx]));
```suggestion
                            AdderBlockUsingTemporaryLogicalAnd(auxRegister[idx-1], xs![idx], ys![idx], auxRegister[idx]);
```

This statement does not need to be controlled, as it is inside a `within` block.

2020-10-25 14:27 UTC, msoeken commented on Standard/src/Arithmetic/Integer.qs
> +                        (Controlled Carry) (controls, (auxRegister[nQubits-2], xs![nQubits-1], ys![nQubits-1], carry));
This `Carry` implementation uses two `CCNOT` gates and could be replaced by something that uses a single `ApplyAnd`. Could `AdderBlockUsingTemporaryLogicalAnd` be used?

2020-10-25 14:27 UTC, msoeken commented on Standard/src/Arithmetic/Integer.qs
> +                (Controlled CNOT) (controls,(xs![0], ys![0]));
It is not clear to me why this line is here. Could you add some line of documentation to make it clearer.

2020-10-25 16:50 UTC, TviNet commented on Standard/src/Arithmetic/Integer.qs
> +                            (Controlled AdderBlockUsingTemporaryLogicalAnd) (controls, (auxRegister[idx-1], xs![idx], ys![idx], auxRegister[idx]));
Thanks for the suggestions
I am using this figure as reference.
![image](https://user-images.githubusercontent.com/24621183/97112476-85fd1680-170a-11eb-9880-5904a90a8bac.png)

The block can be considered to have two parts: ComputeTempCarry and EraseTempCarry.
 To make use of within..apply structure I have used
 ```
AdderBlockUsingTemporaryLogicalAnd =  ComputeTempCarry 
Adjoint AdderBlockUsingTemporaryLogicalAnd  = EraseTempCarry
```
Since the control only affects EraseTempCarry I had to add a Controlled + Adjoint variant.

I realize this has gotten a bit messy and is probably an incorrect usage of adjoint 

So I am planning to use the two blocks (ComputeTempCarry is Adj) and (EraseTempCarry is Adj + Ctl) but this would not make use of within..apply

2020-10-25 16:58 UTC, TviNet commented on Standard/src/Arithmetic/Integer.qs
> +                        (Controlled Carry) (controls, (auxRegister[nQubits-2], xs![nQubits-1], ys![nQubits-1], carry));
`AdderBlockUsingTemporaryLogicalAnd` has to erase the carry bit by design so I don't think it can be used here unless I understand incorrectly.  The first `CCNOT` of  `Carry` can be changed to `ApplyAnd` since the `CarryOut` is zero. I haven't been able to find another implementation that would do better.

2020-10-25 17:02 UTC, TviNet commented on Standard/src/Arithmetic/Integer.qs
> +                (Controlled CNOT) (controls,(xs![0], ys![0]));
Since the first bit has `CarryIn` always zero the operations on first bit can be simplified to 
```
ApplyAnd (xs![0], ys![0], auxRegister[0]);
---<Compute other bits using auxRegister[0]>---
(Adjoint ApplyAnd) (xs![0], ys![0], auxRegister[0]);
(Controlled CNOT) (controls,(xs![0], ys![0]));
```
to reduce the gate count.

2020-10-26 07:49 UTC, msoeken approved these changes
Thanks for your changes and the clarification. I approve this PR and changed the target to a feature branch.

Thanks for your work on this @TviNet

2020-10-26 13:28 UTC, merged