Add ApplyUnitary operation
microsoft/QuantumLibraries pull request #391
Opened 2020-12-21 21:04 UTC by fedimser

2020-12-22 09:15 UTC, msoeken reviewed
Hi @fedimser, you're initial commits look interesting! I left some initial comments.

2020-12-22 09:15 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +                int n = (int)matrices.Count;
```suggestion
                int n = matrices.Count;
```

`Count` already returns `int`.

2020-12-22 09:15 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +                QArray<QArray<Complex>>[] result = new QArray<QArray<Complex>>[n];
```suggestion
                var result = new QArray<QArray<Complex>>[n];
```

2020-12-22 09:15 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +                QArray<Complex>[] a = new QArray<Complex>[n];
```suggestion
                var a = new QArray<Complex>[n];
```

2020-12-22 09:15 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +}
```suggestion
}

```

2020-12-22 09:15 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +        for (i in 0..n-1) {
You could write `for ((matrix, index) in TwoLevelDecomposition(unitary))` here and directly access `matrix` and `index` without a loop index variable.

2020-12-22 09:15 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +            let index2 = idx[i][0];
Here, `index2 == index1`. Is that intended?

2020-12-22 09:15 UTC, msoeken commented on Standard/tests/Synthesis/UnitaryDecompositionTest.qs
> +    operation ApplyUnitaryToRegister(matrix: Complex[][], qubits: Qubit[]) : Unit {
```suggestion
    internal operation ApplyUnitaryToRegister(matrix: Complex[][], qubits: Qubit[]) : Unit {
```

2020-12-22 09:15 UTC, msoeken commented on Standard/tests/Synthesis/UnitaryDecompositionTest.qs
> +    operation CheckOperation(matrix: Complex[][], expected: (Qubit[] => Unit is Adj)) : Unit {
```suggestion
    internal operation CheckOperation(matrix: Complex[][], expected: (Qubit[] => Unit is Adj)) : Unit {
```

2020-12-22 09:15 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +    function TwoLevelDecomposition(unitary: Complex[][]) : (Complex[][][], Int[][]) {
```suggestion
    internal function TwoLevelDecomposition(unitary: Complex[][]) : (Complex[][][], Int[][]) {
```

2020-12-22 09:15 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +    operation ApplyFlips(flipMask: Int, qubits : LittleEndian) : Unit is Adj + Ctl  {
```suggestion
    internal operation ApplyFlips(flipMask: Int, qubits : LittleEndian) : Unit is Adj + Ctl  {
```

2020-12-22 09:15 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +    public partial class TwoLevelDecomposition {
```suggestion
    internal partial class TwoLevelDecomposition {
```

2020-12-22 14:00 UTC, fedimser commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +        for (i in 0..n-1) {
Result of that function is not array of tuples, but tuple of arrays. However, maybe I should make it array of tuples.

2020-12-22 14:10 UTC, fedimser commented
Thanks for the review.
This PR is work in progress, so I converted it to draft.

2020-12-22 16:12 UTC, fedimser commented
@msoeken, can you please advice which linear algebra library I can use in the C# code?
All I need is to be able to represent complex matrices and matrix multiplication. I can implement it from scratch on top of C# arrays, but I would prefer to use some C# equivalent of NumPy.

2020-12-22 16:14 UTC, msoeken commented
@fedimser I don't have much experience with NumPy alternatives in .NET, but you can see if [NumSharp](https://github.com/SciSharp/NumSharp) has the operations you need.

2021-01-04 17:42 UTC, msoeken requested changes
Thanks a lot @fedimser, this is great work! I left some comments, mostly formatting and some suggestions.

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/MatrixUtils.cs
> +        public static bool isMatrixUnitary(Complex[,] matrix)
```suggestion
        public static bool IsMatrixUnitary(Complex[,] matrix)
```

C# language style uses capital method names.

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/MatrixUtils.cs
> +                    if ((dotProduct - expectedDotProduct).Magnitude > 1e-9)
I suggest to extract the threshold as a parameter with a default value. Most of the accuracy thresholds in Q# are `1e-10`.

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/MatrixUtils.cs
> +        public static QArray<QArray<Quantum.Math.Complex>> matrixToQs(Complex[,] b)
```suggestion
        public static QArray<QArray<Quantum.Math.Complex>> MatrixToQs(Complex[,] b)
```

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/MatrixUtils.cs
> +        public static Complex[,] squareMatrixFromQs(IQArray<IQArray<Quantum.Math.Complex>> a)
```suggestion
        public static Complex[,] SquareMatrixFromQs(IQArray<IQArray<Quantum.Math.Complex>> a)
```

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/TwoLevelUnitary.cs
> +            Debug.Assert(MatrixUtils.isMatrixUnitary(mx), "Matrix is not unitary");
```suggestion
            Debug.Assert(MatrixUtils.IsMatrixUnitary(mx), "Matrix is not unitary");
```

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/TwoLevelUnitary.cs
> +            return (mx[0, 0] - 1).Magnitude < 1e-9 && mx[0, 1].Magnitude < 1e-9 &&
See comment above thresholds above.

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/TwoLevelUnitary.cs
> +}
```suggestion
}

```

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/TwoLevelUnitary.cs
> +            return (MatrixUtils.matrixToQs(this.mx), this.i1, this.i2);
```suggestion
            return (MatrixUtils.MatrixToQs(this.mx), this.i1, this.i2);
```

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +            private static int[] grayCode(int n)
Great implementation!

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +        if(AbsD(phi) > 1e-9) {R1(phi, qubit);}
```suggestion
        if (AbsD(phi) > 1e-9) { R1(phi, qubit); }
```

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +        set flipMasks w/= 0 <- 0;
```suggestion
        mutable flipMasks = ConstantArray(n + 1, 0);
```

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +        }
```suggestion
        for ((i, (_, _, i2)) in Enumerated(decomposition)) {
            set flipMasks w/= (i+1) <- (allQubitsMask - i2); 
        }
```

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +        }
```suggestion
        ApplyXorInPlace(flipMask, qubits);
```
I think that these two do the very same thing.

2021-01-04 17:42 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +            let (matrix, i1, i2) = decomposition[i];
```suggestion
        // i1, i2 - indices of non-trivial 2x2 submatrix of two-level unitary matrix being 
        // applied. 
        // i1 and i2 differ in exactly one bit; i1 < i2.
        // matrix - 2x2 non-trivial unitary submatrix of said two-level unitary.
        for ((i, (matrix, i1, i2)) in Enumerated(decomposition)) {
```

2021-01-04 20:27 UTC, cgranade requested changes
Thanks for doing this, we really appreciate your contribution! I've marked as request changes for some of the required modifications (e.g.: copyright headers), but I'm happy to help expand on or implement any of my comments.

Since this PR modifies the Q# API, I'll also go on and schedule it for the next [API Review Meeting](https://github.com/microsoft/QuantumLibraries/projects/1), and will comment here accordingly following that meeting. Thank you!

2021-01-04 20:27 UTC, cgranade commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +    // For convenience prepends result with 0.
It may be helpful to turn this into a brief API documentation comment.

```suggestion
    /// # Summary
    /// For every 2-level unitary calculates "flip mask", which denotes qubit which should 
    /// be inverted before and after applying corresponding 1-qubit gate.
    /// For convenience prepends result with 0.
```

2021-01-04 20:27 UTC, cgranade commented on Standard/tests/Synthesis/UnitaryDecompositionTest.qs
> +    operation ApplyUnitary_Identity () : Unit {
In general, the Q# style guide suggests against using `_` in operation and function names. In this case, I'd suggest that since this operation does more than just applying the identity operation, but also checks that the operation is correct, it may be helpful to rename to something like `CheckApplyUnitaryAppliesIdentity`. While that is a bit verbose, this operation isn't directly called in user code (not part of the Q# API), and verbose names can be helpful in reading through error logs.

2021-01-05 06:59 UTC, msoeken commented on Standard/src/Synthesis/TwoLevelUnitary.cs
> +        }
@cgranade, should it be `=>` instead of `=` in line 66?

2021-01-05 07:19 UTC, cgranade commented on Standard/src/Synthesis/TwoLevelUnitary.cs
> +        }
Yes, absolutely. Thanks for catching my typo, @msoeken!

2021-01-05 07:19 UTC, cgranade commented on Standard/src/Synthesis/TwoLevelUnitary.cs
> +        }
I've edited the suggestion accordingly.

2021-01-05 20:14 UTC, fedimser commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +        }
Nice function! In that case I don't ned ApplyFlips and can call ApplyXorInPlace instead.

2021-01-05 21:15 UTC, fedimser commented on Standard/src/Synthesis/TwoLevelUnitary.cs
> +        }
Done.

2021-01-05 21:46 UTC, fedimser commented on Standard/src/Synthesis/MatrixUtils.cs
> +                    if ((dotProduct - expectedDotProduct).Magnitude > 1e-9)
Done.

2021-01-05 21:46 UTC, fedimser commented on Standard/src/Synthesis/TwoLevelUnitary.cs
> +            return (mx[0, 0] - 1).Magnitude < 1e-9 && mx[0, 1].Magnitude < 1e-9 &&
Done.

2021-01-05 21:49 UTC, fedimser commented on Standard/tests/Synthesis/UnitaryDecompositionTest.qs
> +    operation ApplyUnitary_Identity () : Unit {
Changed all test cases names to CheckApplyUnitaryApplies...

2021-01-06 07:53 UTC, msoeken reviewed
Looks great to me, thanks! I left some few comments.

2021-01-06 07:53 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +        if (AbsD(mu - lmbda) > 1e-9) { Rz(mu - lmbda, qubit); }
Can we also use 1e-10 here as tolerance value?

2021-01-06 07:53 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.qs
>          if (AbsD(lmbda + mu) > 1e-9) { Rz(- lmbda - mu, qubit); }
```suggestion
        if (AbsD(lmbda + mu) > 1e-9) { Rz(-lmbda - mu, qubit); }
```

2021-01-06 19:50 UTC, fedimser commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +        if (AbsD(mu - lmbda) > 1e-9) { Rz(mu - lmbda, qubit); }
Done.

2021-01-06 19:51 UTC, fedimser commented on Standard/src/Synthesis/UnitaryDecomposition.qs
>          if (AbsD(lmbda + mu) > 1e-9) { Rz(- lmbda - mu, qubit); }
Done.

2021-01-06 23:28 UTC, fedimser commented
Hi Mathias,

I addressed your comments.
Also I have found a bug in my algorithm, which I fixed in my Python repository, as well as here.
I added one more test for 8x8 matrix which is equivalent to 4 controlled gates (this test helped me find a bug).

One more thing to double check is that my algorithm indeed applies matrix to little-endian register. The easiest way to check that is to see what is matrix for CNOT gate, and I have a test for that.
So, if you give this matrix to ApplyUnitary:
[[1, 0, 0, 0],
 [0, 0, 0, 1],
 [0, 0, 1, 0],
 [0, 1, 0, 0]],
then it will apply operation equivalent to CNOT(q[0], q[1]).
We can see that it swaps states 1 and 3, i.e. states with the lowest bit equal to 1. Which means qubit corresponding to thelowest bit is control qubit. And we see that control qubit is q[0]. So, the qubit with index 0 encodes the lowest bit, as it should.

2021-01-07 06:53 UTC, msoeken reviewed
Just some formatting suggestions.

2021-01-07 06:53 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +                            }
```suggestion
                            if (j == i + 1)
                            {
                                mx = new Complex[,] { { 1/a, 0.0 }, { 0.0, a } };
                            }                            
```

2021-01-07 06:53 UTC, msoeken commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +                            }
```suggestion
                            if (j == i + 1)
                            {
                                mx = new Complex[,] { { 0.0, b }, { 1/b, 0.0 } };
                            } 
```

2021-01-07 06:53 UTC, msoeken commented on Standard/tests/Synthesis/UnitaryDecompositionTest.qs
> +    operation CheckApplyUnitaryAppliesFourControlledGates () : Unit {
```suggestion
    operation CheckApplyUnitaryAppliesFourControlledGates() : Unit {
```

2021-01-07 09:32 UTC, fedimser commented on Standard/tests/Synthesis/UnitaryDecompositionTest.qs
> +    operation CheckApplyUnitaryAppliesFourControlledGates () : Unit {
Done.

2021-01-07 09:32 UTC, fedimser commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +                            }
Done.

2021-01-07 09:32 UTC, fedimser commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +                            }
Done.

2021-01-12 06:12 UTC, cgranade approved these changes
This looks really good, thanks for the contribution! I've left a few last comments as suggestions that would be good to bring in before merging this to `main`, but otherwise I think this is getting pretty close now that the API review has completed.

Thank you again!

2021-01-12 06:12 UTC, cgranade commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +            }
You may not need to collect in a `List` here, either. Using the `yield return` statement (very similar to Python's `yield`), you can write this out directly as an enumerable over `TwoLevelUnitary`:

```suggestion
            private static IEnumerable<TwoLevelUnitary> twoLevelDecomposeGray(Complex[,] A)
            {
                int n = A.GetLength(0);
                Debug.Assert(A.GetLength(1) == n, "Matrix is not square.");
                Debug.Assert(MatrixUtils.IsMatrixUnitary(A), "Matrix is not unitary.");

                int[] perm = GrayCode(n);
                A = PermuteMatrix(A, perm);
                foreach (TwoLevelUnitary matrix in  TwoLevelDecompose(A))
                {
                    matrix.ApplyPermutation(perm);
                    matrix.OrderIndices();
                    yield return matrix;
                }
            }
```

Using the same technique in `TwoLevelDecompose` should allow you to avoid allocating a list for any intermediate steps, only allocating in the constructor call at line 168.

2021-01-12 07:08 UTC, msoeken approved these changes

2021-01-12 20:05 UTC, fedimser commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +            }
Done.

2021-01-12 20:06 UTC, fedimser commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +            private static List<TwoLevelUnitary> twoLevelDecomposeGray(Complex[,] A)
Done.

2021-01-12 20:08 UTC, fedimser commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +        }
Done.

2021-01-12 20:32 UTC, fedimser commented on Standard/src/Synthesis/UnitaryDecomposition.qs
> +    operation ApplyUnitary(unitary: Complex[][], qubits : LittleEndian) : Unit is Adj + Ctl {
Done. 
Added internal function SquareMatrixFact.

Strictly speaking, I would also have to add a check that matrix is unitary (which is already present in Q#). But it's non-trivial  and it's complexity is O(N^3), so I would like avoid implementing and running it twice. 
So I hope it's fine to check that matrix is unitary only in C#.

2021-01-12 20:32 UTC, fedimser commented on Standard/src/Synthesis/UnitaryDecomposition.cs
> +                Debug.Assert(A.GetLength(1) == n, "Matrix is not square.");
Added check that matrix is square in Q#.

2021-01-12 20:45 UTC, fedimser commented
@cgranade, I addressed your comments. I think this PR is now ready to be merged.

2021-01-12 22:09 UTC, cgranade approved these changes
Looks good, thank you for the contribution! ♥

2021-01-12 22:09 UTC, cgranade commented
/azp run

2021-01-13 21:52 UTC, cgranade commented
/azp run

2021-01-14 06:54 UTC, merged