lookup table code
microsoft/QuantumLibraries pull request #611
Opened 2022-08-04 15:58 UTC by rajkk1

2022-08-19 07:15 UTC, msoeken requested changes
Thanks for the contribution. That looks really great! I left some comments.

2022-08-19 07:15 UTC, msoeken commented on Numerics/src/FixedPoint/LookupTable.qs
> +    newtype MakeLookupReturn = (
```suggestion
    newtype FunctionWithLookupTable = ( 
```

2022-08-19 07:15 UTC, msoeken commented on Numerics/src/FixedPoint/LookupTable.qs
> +    /// # Summary
I'd break down the long `#Summary` section into `#Summary` and `#Remarks`

2022-08-19 07:15 UTC, msoeken commented on Numerics/src/FixedPoint/LookupTable.qs
> +    /// it will compute f'(x') where f' is an approximation of f with a maximum error of epsOut and x' is an
The documentation supports the use of inline LaTeX for formulas.

2022-08-19 07:15 UTC, msoeken commented on Numerics/src/FixedPoint/LookupTable.qs
> +    function MakeLookup(func: Double -> Double, domain: (Double, Double), epsIn: Double, epsOut: Double, numSwapBits: Int): MakeLookupReturn {
```suggestion
    function ApplyFunctionWithLookupTable(func: Double -> Double, domain: (Double, Double), epsIn: Double, epsOut: Double, numSwapBits: Int): FunctionWithLookupTable {
```

2022-08-19 07:15 UTC, msoeken commented on Numerics/src/FixedPoint/LookupTable.qs
> +        return MakeLookupReturn(
```suggestion
        return FunctionWithLookupTable(
```

2022-08-19 07:15 UTC, msoeken commented on Numerics/src/FixedPoint/LookupTable.qs
> +    /// at this is that in step in the SELECT section of the circuit in Fig 1c of arXiv:1812.00954, we will encode 2^numSawpBits
```suggestion
    /// at this is that in step in the SELECT section of the circuit in Fig 1c of arXiv:1812.00954, we will encode 2^numSwapBits
```

2022-08-19 07:15 UTC, msoeken commented on Numerics/src/FixedPoint/LookupTable.qs
> +    /// # Potential improvements TODO
I suggest to make them normal comments inside the operation instead of doc comments.

2022-08-19 07:15 UTC, msoeken commented on Numerics/src/FixedPoint/LookupTable.qs
> +        // MultiplexOperationsWithUnaryIteration(unitaries, LittleEndian(addressRegister), outputRegister);
```suggestion
```

2022-08-19 07:15 UTC, msoeken commented on Numerics/src/FixedPoint/LookupTable.qs
> +    /// Impelements an efficient control swap (with 2 CNOTs and one CCNOT)
```suggestion
    /// Implements an efficient control swap (with 2 CNOTs and one CCNOT)
```

2022-08-19 07:15 UTC, msoeken commented on Numerics/tests/LookupTableTests.qs
> +        let lookup = MakeLookup(ExpD, (xMin, xMax), epsIn, epsOut, numSwapBits);
```suggestion
        let lookup = ApplyFunctionWithLookupTable(ExpD, (xMin, xMax), epsIn, epsOut, numSwapBits);
```

2022-08-19 07:15 UTC, msoeken commented on Numerics/tests/LookupTableTests.qs
> +            Message($"{inResult} {outResult}");
```suggestion
```

2022-08-19 07:15 UTC, msoeken commented on Numerics/tests/LookupTableTests.qs
> +}
```suggestion
}

```

2022-08-19 07:15 UTC, msoeken commented on Numerics/tests/LookupTableTests.qs
> +            Message($"Input value: {inputResult}, Output value:{outputResult}");
```suggestion
```

2022-08-19 07:15 UTC, msoeken commented on Numerics/tests/LookupTableTests.qs
> +        let lookup = MakeLookup(func, (xMin, xMax), epsIn, epsOut, 0);
```suggestion
        let lookup = FunctionWithLookupTable(func, (xMin, xMax), epsIn, epsOut, 0);
```

2022-08-19 13:57 UTC, rajkk1 commented on Numerics/tests/LookupTableTests.qs
> +}
Oh this is a strange one! Was there an extra curly brace? It seemed to run fine on my end when I last tried it

2022-08-19 15:24 UTC, msoeken commented on Numerics/tests/LookupTableTests.qs
> +}
No, that's just an extra blank line at the end of the file.

2022-08-19 15:57 UTC, rajkk1 commented on Numerics/tests/LookupTableTests.qs
> +}
Oh got it!

2022-08-21 10:22 UTC, rajkk1 commented on Numerics/src/FixedPoint/LookupTable.qs
> +    /// # Potential improvements TODO
Fair! I have moved both potential improvements to inside the comments lines 153 and 303

2022-08-21 10:27 UTC, rajkk1 commented on Numerics/src/FixedPoint/LookupTable.qs
> +    /// # Summary
Done!

2022-08-21 10:28 UTC, rajkk1 commented on Numerics/src/FixedPoint/LookupTable.qs
> +    /// it will compute f'(x') where f' is an approximation of f with a maximum error of epsOut and x' is an
Added inline LaTeX tags and also split it into a remarks section as well

2022-08-22 11:53 UTC, msoeken approved these changes
Thanks for incorporating the comments. I have left one more comment that includes an example for the docs.

2022-08-22 11:53 UTC, msoeken commented on Numerics/src/FixedPoint/LookupTable.qs
> +    /// encoded
```suggestion
    /// encoded 
    ///
    /// # Example
    /// The following code creates a quantum operation based on `ExpD` in the (inclusive) range from `-5.0` to `5.0` with an input error of `1e-3` and an output error of `1e-4`. It uses `2` SWAP bits for the implementation.
    ///
    /// ```qsharp
    /// // Create operation from lookup table
    /// let domain = (-5.0, 5.0);
    /// let epsIn = 1e-3;
    /// let epsOut = 1e-4;
    ///
    /// let lookup = ApplyFunctionWithLookupTable(ExpD, domain, epsIn, epsOut, 2);
    ///
    /// // Allocate qubits
    /// use input = Qubit[lookup::IntegerBitsIn + lookup::FractionalBitsIn];
    /// use output = Qubit[lookup::IntegerBitsOut + lookup::FractionalBitsOut];
    ///
    /// // Represent qubit registers as fixed points
    /// let inputFxP = FixedPoint(lookup::IntegerBitsIn, input);
    /// let outputFxP = FixedPoint(lookup::IntegerBitsOut, output);
    ///
    /// // Apply operation
    /// lookup::Apply(inputFxP, outputFxP);
    /// ```
```

2022-08-22 12:53 UTC, msoeken commented
/azp run

2022-08-22 16:29 UTC, msoeken commented
/azp run

2022-08-22 17:12 UTC, msoeken commented
/azp run

2022-08-23 06:30 UTC, merged

2022-08-23 07:48 UTC, rajkk1 commented
Woohoo!!

Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., août 23, 2022 à 8:30, Mathias ***@***.***> a écrit:   


Merged #611 into main.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>